### ISSUE TITLE
[Darwin]: LHPrepareRemapMachMem Question

### ISSUE THREAD

**Issue by DerekSelander** [coolstar/libhooker#1]
More for learning curiosity here: Why not call [mach_]vm_remap here? What do you get hand rolling your own mach_msg implementation? 

https://github.com/coolstar/libhooker/blob/4f85a68daebaf7456c66e1f55184dca118022397/libhooker/mem/writeMem-darwin.c#L191-L221

Thanks

**Comment by coolstar** [comment]
If a tweak tries hooking libSystem on the same page as mach_msg / vm_remap / vm_protect, it would crash as soon as it trues calling vm_remap / mach_msg because the page would be marked as non-executable when it's marked as writable prior to that.

Hence the custom implementation since we can't trust the system one isn't overwritten / inaccessible halfway through.
